version: '3'

services:
  web:
    build: ./mySampleProject
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./mySampleProject:/code
      # - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    expose: [8000]
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psqlpass123
      POSTGRES_DB: djangodb

volumes:
  postgres_data: