version: '3'

services:
  web:
    build: ./mySampleProject
    command: gunicorn mySampleProject.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./mySampleProject:/code
      - static_volume:/code/staticfiles
    ports:
      - "8001:8001"
    expose: [8001]
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psqlpass123
      POSTGRES_DB: djangodb
  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    depends_on:
      - web
    volumes:
      - static_volume:/code/staticfiles

volumes:
  postgres_data:
  static_volume: